version: "3.9"
services:
  flask_modern_db:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./flask_session:/app/flask_session
    env_file:
      - .env  # Load environment variables from .env file (recommended)
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=production
      # You can also set variables here or in .env
      # - OPENROUTER_API_KEY=your_openrouter_api_key_here
      # - OPENROUTER_API_URL=https://openrouter.ai/api/v1
      # - AI_MODEL=qwen/qwen3-235b-a22b:free
